a,b,c=input().split(" ")
a=float(a)
b=float(b)
c=float(c)
print("TRIANGULO: {:.3F}".format(.5*a*c))
print("CIRCULO: {:.3F}".format(3.14159*c*c))
print("TRAPEZIO: {:.3F}".format(.5*(a+b)*c))
print("QUADRADO: {:.3F}".format(b*b))
print("RETANGULO: {:.3F}".format(a*b))
